# See https://pre-commit.com for more information
repos:
  # Only the most basic file hygiene - these rarely fail
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe] # More forgiving YAML checking
      - id: check-toml

  # Black - auto-fixes code formatting, so it rarely blocks
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.12

  # isort - auto-fixes import order, so it rarely blocks
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
# Intentionally REMOVED:
# - flake8 (can be strict about code quality)
# - mypy (very strict in your config - will block commits)
