name: CI Pipeline

on:
  push:
    # branches: [ main, develop ]
  pull_request:
    # branches: [ main, develop ]
    # types: [ opened, synchronize, reopened ]

env:
  PYTHON_VERSION: '3.12'
  POETRY_VERSION: '1.7.1'
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpass
  REDIS_HOST: localhost
  REDIS_PORT: 6379

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Suite
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build development containers
        run: |
          docker compose -f docker-compose.dev.yml build
          docker compose -f docker-compose.dev.yml up -d

      - name: Wait for services to be ready
        run: |
          # Wait for PostgreSQL
          timeout 30s bash -c 'until docker exec fastapi-auth-postgres-dev pg_isready; do sleep 1; done'
          # Wait for Redis
          timeout 30s bash -c 'until docker exec fastapi-auth-redis-dev redis-cli ping; do sleep 1; done'

      - name: Run unit tests
        run: docker exec fastapi-auth-app-dev pytest tests -v --cov=app --cov-report=xml --cov-report=html --cov-report=term

      - name: Run integration tests
        run: docker exec fastapi-auth-app-dev pytest tests/integration -v

      - name: Run e2e tests
        run: docker exec fastapi-auth-app-dev pytest tests/e2e -v

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.dev.yml down -v



  dependency-review:
    runs-on: ubuntu-latest
    name: Dependency Review
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
